version: "3.5"
services:
  bgpguard-python:
    build:
      context: ./
      dockerfile: dockerfiles/bgpguard-python-dev
    stdin_open: true
    ports:
      - 5000:5000
    environment: 
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    command: "flask run"
    #tty: true
    restart: "no" 
networks:
  default:
    name: bgpguard-net 